import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {MainLayout} from '../components/templates'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        Hello
      </MainLayout>
      
    </>
  )
}

export default Home
